### PR TITLE
M_mem_rmem: check that needle len is not greater than haystack len

### PR DESCRIPTION
**Pull request by snhilde**
swap lengths

### CODE REVIEW

**Comment by bradh352** [comment]
wonder how this was missed, it would pretty much mean this function never worked, no?

 can you add a test case?

**Comment by user-none** [comment]
I guess nothing is using this function.

**Comment by snhilde** [comment]
Latest commit allows matches at very end of haystack

**Comment by snhilde** [comment]
Are you looking for tests in test/base/* ?

**Comment by user-none** [comment]
> Are you looking for tests in test/base/* ?

/test mirrors the dir structure of the root.

**Pull request merged**
