### PR TITLE
Add logic to M_http_simple_read_codec() to work better

### PR DESCRIPTION
**Pull request by SCI4THIS**
modified:   m_http_simple_reader.c

### CODE REVIEW

**Comment by user-none** [comment]
Not sure why you're doing this in the first place when m_http.c func M_http_update_ctype() already parses the content type header. Are you hitting a bug where m_http isn't properly setting the codec?

**Comment by SCI4THIS** [comment]
Yes, it was always returning INVALID

**Comment by user-none** [comment]
Also, you're assuming a charset will be set in the header. This is not always the case, "application/x-www-form-urlencoded" content type often does not set a charset. The charset can also be set in the html instead of in the header. Every time this function is called, you will attempt to parse the header if no charset was in the header.

**Comment by SCI4THIS** [comment]
Oh, M_http_update_ctype() is what I want to do.

**Comment by user-none** [comment]
> Oh, M_http_update_ctype() is what I want to do.

Right. See if that function isn't being called for some reason. And if it is why it's not reading the charset from the content type correctly.

**Comment by SCI4THIS** [comment]
Not sure if that is relevent

**Pull request closed without merging**
